### ISSUE TITLE
Video Element Invisible (edit: when no class vlite-js is given)

### ISSUE THREAD

**Issue by bfiessinger** [yoriiis/vlitejs#33]
https://codesandbox.io/s/kind-water-s0dzq?file=/index.html

The video Element is currently invisible when using vlitejs. It appears to display straight under the vlite wrapper.

```css
.v-vlite > video {
  position: absolute;
  width: 100%;
  left: 0;
  top: 0;
}
```

would fix it.

Edit: I just found out that it's important to add the `vlite-js` class to video elements. This should be either passed by the library or better described in the docs imo.
